name: sync-fork
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Sync fork with upstream
        id: sync
        run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
        continue-on-error: true

      - uses: actions/checkout@v4
      - name: Handle sync failure and resolve conflicts
        if: steps.sync.outcome == 'failure'
        run: |
          echo "Sync failed, handling conflicts..."
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch https://github.com/asdlokj1qpi233/subconverter.git
          git checkout FETCH_HEAD -- .
          git add .
          git commit -m '自动解决合并冲突'
          git push
